defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: "val/acc"  # name of the logged metric which determines when model is improving
  mode: "max"  # can be "max" or "min"
  save_top_k: 1  # save k best models (determined by above metric)
  save_last: True  # additionally always save model from last epoch
  verbose: False
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/acc"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1