name: Train Model and Deploy to HuggingFace

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        python dogbreed_classify/src/train.py

    - name: Create traced_models directory if not exists
      run: mkdir -p dogbreed_classify_gradio/traced_models

    - name: Copy trained model
      run: |
        cp traced_models/model_tracing.pt dogbreed_classify_gradio/traced_models/

    - name: Log in to Hugging Face
      run: python -c 'import huggingface_hub; huggingface_hub.login(token="${{ secrets.hf_token }}")'

    - name: Deploy to Spaces
      run: |
        cd dogbreed_classify_gradio
        gradio deploy
